### ISSUE TITLE
Lazier cloning

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#11444]
### What would you like Renovate to be able to do?

Defer git cloning until the latest possible moment, and ideally avoiding it altogether, in order to reduce average job time and network transfer.

### If you have any ideas on how this should be implemented, please tell us here.

This which trigger a clone today:
- Init (config)
- Re-scanning (extracting)
- Presence of branches

For init:
- [ ] If the default branch SHA has changed, use the API if it exist to get a list of changed files. If the config file hasn't changed, then we have revalidated its contents

For extracting, for each manager we should calculate the manager fingerprint, the resolved manager config, and the matching fileList. If any of those three change for any of the managers then we can re-scan them all. Explaining:
- [ ] #11426 We want to "fingerprint" managers automatically and re-extract just to be safe if any of their implementation details changed
- [ ] #9929 We should isolate only the extract fields of the config, so that we don't unnecessarily trigger rescans for config which is unrelated to the extract results
- [ ] If the file list changes, then naturally we should check the change
The above could/should be combined into a single hash value representing the cache. Only managers with 1 or more matching files should be included in the cache calculation.

For branches/updating:
- [ ] #11445 We should save the state of each branch into cache and reuse it if possible
- [ ] If all branches can be reused, then we can skip cloning

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by rarkins** [comment]
This is already described in sub-issues
