### ISSUE TITLE
Azure - Some methods not implemented

### ISSUE THREAD

**Issue by jycouet** [renovatebot/renovate#1149]
List of VSTS platform methods not implemented:

- [x] `addAssignees` => Can't add Assignees to the PR
- [x] `addReviewers` => Can't add Reviewers to the PR
- [x] `getPrFiles` => Cannot rebase modified PRs
- [x] `setBranchStatus` => unpublishSafe not supported #7392
- [x] `mergeBranch` => Means automerge branch is not supported
- [x] `mergePr` => Means automerge PR is not supported #7908 
- [x] `getBranchStatusCheck` => only partial #7392
- [x] `getBranchStatus` => only partial #7392

I'll look at this later, if some people request it! :)

**Comment by DavidParks8** [comment]
+1

**Comment by viceice** [comment]
branch status can be used [api](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/statuses?view=azure-devops-rest-4.1)

**Comment by JamieMagee** [comment]
Looks like we're just missing `mergePr` 🎉

There are also `findIssue`, `ensureIssue`, `ensureIssueClosing`, and `getIssueList`, but those are intentionally not implemented due to all the different ways teams can setup work item requirements. It's the reason the `azureWorkItemId` configuration option exists.

**Comment by wiruzman** [comment]
How about auto-resolve work item setting when pull request is merged? (blue line)
![image](https://user-images.githubusercontent.com/7511734/108338147-39b47580-71d6-11eb-9372-b7b3759464e0.png)

**Comment by rarkins** [comment]
> How about auto-resolve work item setting when pull request is merged? (blue line)

I think most users have a long-running work item which is shared between all PRs. Do you somehow have multiple/dynamic ones for each PR?

**Comment by wiruzman** [comment]
> > How about auto-resolve work item setting when pull request is merged? (blue line)
> 
> I think most users have a long-running work item which is shared between all PRs. Do you somehow have multiple/dynamic ones for each PR?

When I mention work item, it is a task or bug, they should be short-living work items. However it is true that user stories are long-running. But having the option to use it or not should be available in the configuration, then whoever want to use it that functionality from Azure DevOps is free to do that.

One good example is `azureAutoComplete`.

**Comment by rarkins** [comment]
Unless Renovate is creating work items per-PR, I don't see how you would have a 1:1 mapping. And if you don't, then closing the work item after each PR would be a mistake.

> But having the option to use it or not should be available in the configuration, then whoever want to use it that functionality from Azure DevOps is free to do that.

We add features if we think they are a good idea, not just because they're possible.

**Comment by wiruzman** [comment]
We actually create a work item pr pull request. That is why the value of closing the work item is highly requested.

**Comment by rarkins** [comment]
Please explain your workflow in detail. e.g. do you manually create a work item for each PR *after* the PR is created? Or if you create one beforehand per PR, how do you achieve that?

**Comment by JamieMagee** [comment]
@wiruzman I understand the requirement of creating a separate work item per pull request, but in Azure DevOps teams can configure different fields to be filled in, and the logic for doing that automatically is outside the scope of Renovate. For that reason, we recommend, as @rarkins noted, to maintain a long-running work item to link Renovate pull requests to.

We could implement "Complete associated work items after merging", but you'd still be required to create those work items yourself and manually link them to each pull request.

---

On another note, `mergePr` was implemented in #7908. So aside from the methods we explicitly haven't implemented due to platform limitations, Azure DevOps is now feature complete 🎉

**Comment by wiruzman** [comment]
> Please explain your workflow in detail. e.g. do you manually create a work item for each PR _after_ the PR is created? Or if you create one beforehand per PR, how do you achieve that?

Our workflow in Azure Pipelines is:
- Renovate creates pull requests
- Using an Azure Function to determine all active pull requests without a work item and creates them and attach it to pull request using Azure DevOps REST API.

**Comment by rarkins** [comment]
When you are attaching the work item to the PR, can you also update the PR to auto-complete?

**Comment by wiruzman** [comment]
> When you are attaching the work item to the PR, can you also update the PR to auto-complete?

That is also a solution :)
