### ISSUE TITLE
Try out Vale linter for our Markdown files

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#14835]
### Describe the proposed change(s).

Find out if Vale will work for us.

## Introduction

Vale is a command line tool to lint our Markdown files for style errors.
The project can be found on GitHub: https://github.com/errata-ai/vale

## Todos:

- [x] Try out Vale with default settings
- [x] Find way to run Vale in Gitpod container (run `brew install vale`)
- [x] Find way to run Vale in `.devcontainer` on GitHub
- [x] Find out how enforce the [Plain language guidelines](https://www.plainlanguage.gov/guidelines/) with Vale
- [x] Find out how to customize the allowed/rejected vocabulary lists
- [ ] Setup GitHub Action for Vale linter on main repository
- [ ] Setup GitHub Action for Vale linter on docs publishing repository
- [ ] Pin version of Vale everywhere we use it:
  - [ ] Gitpod
  - [ ] GitHub Codespaces
  - [ ] GitHub Action file(s)

**Comment by HonkingGoose** [comment]
@viceice or @rarkins Is the `brew` package manager pre-installed in your codespaces enviroment? On Gitpod `brew` comes with their default image, but I don't know how you've set up your Codespaces. 😉

**Comment by viceice** [comment]
we don't need brew, as the required binary can be easily downloaded from releases page

**Comment by HonkingGoose** [comment]
@viceice Does GitHub Codespaces come with the official [`gh` CLI program](https://cli.github.com/)? The Vale docs say:

> If you want to use Vale with a CI service, we recommend that you use the official [GitHub CLI tool](https://cli.github.com/) to download the version of your choice from the [releases page](https://github.com/errata-ai/vale/releases)
> 
> ```bash
> $ gh release download --repo 'errata-ai/vale' -p 'vale_2.11.2_Linux_64-bit.tar.gz'
> $ tar -xf 'vale_2.11.2_Linux_64-bit.tar.gz'
> $ ./vale -v
> ```
> 
> This will ensure that your CI builds are consistent and allow you to update versions on an opt-in basis.

**Comment by viceice** [comment]
nope, we can easily add an installer to our buildbpack, so updates are supported out of the box 🤗

**Comment by JamieMagee** [comment]
It can also be run as a Docker container. That would simplify the install process.

**Comment by rarkins** [comment]
> It can also be run as a Docker container. That would simplify the install process.

But that means a dev would need Docker locally to run all tests?

**Comment by rarkins** [comment]
This is another reason I'd love to have seamless codespaces or gitpod for this project so that drive by contributors can easily test their changes

**Comment by HonkingGoose** [comment]
## Adding installer to our buildpack

> we don't need `brew`, as the required binary can be easily downloaded from releases page

> nope, we can easily add an installer to our buildpack, so updates are supported out of the box 🤗

I found these files in the repository:

https://github.com/renovatebot/renovate/blob/a8930b72563b5049a4e508af242298f07a85fd10/.devcontainer/devcontainer.json#L1-L19

https://github.com/renovatebot/renovate/blob/a8930b72563b5049a4e508af242298f07a85fd10/.devcontainer/Dockerfile#L1-L6

So I think you want to edit the Dockerfile so it fetches the Vale program from their GitHub releases?

## Running Vale as a Docker container

> It can also be run as a Docker container. That would simplify the install process.

Gitpod supports a custom Dockerfile [^gitpod-docker], which we could use to load the official Vale Docker image. But I got stuck trying to create a custom Dockerfile for our basic Gitpod config, see: #12210, so I'm not really keen on messing with that again. 😄🙈 

[^gitpod-docker]: https://www.gitpod.io/docs/config-docker

## Version control for Vale

We should pin the version of Vale in all our files that will end up using Vale:

- Gitpod
- Codespaces
- GitHub Action

I'll add a todo to my list in the original post, so we don't forget this.
