### ISSUE TITLE
Improve docs on how to fetch release notes for Docker images

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#15052]
### Describe the proposed change(s).

Follow up for https://github.com/renovatebot/renovate/pull/14972#discussion_r844447507.

@astellingwerf said:

> With this write up, it remains unclear what I need to do to e.g. my docker images to get Renovate to look up their release notes.

It looks like we need to improve our docs.

**TODO:**

- [ ] Search for documentation on fetching release notes in general
- [ ] Search the docs for the term `Docker` and check if it mentions release notes at all
- [ ] If needed: open PR to improve docs

**Comment by astellingwerf** [comment]
Thanks @HonkingGoose for creating this ticket. My assumption was that those who publish a package (in this case a docker container) need to annotate it with some metadata that points to the GitHub or GitLab project that then exposes the changelog. Is that a fair assumption?

**Comment by viceice** [comment]
here: 

https://github.com/renovatebot/renovate/blob/main/lib/modules/datasource/docker/readme.md

**Comment by rarkins** [comment]
Seems we've described it reasonably well, but maybe we can use our own image as an example. @astellingwerf anywhere else you'd expect to look for such info in our docs where we can link from?

**Comment by HonkingGoose** [comment]
Maintainers, can you give me the example of how you've setup the `renovate/renovate` image with the correct metadata?

I can then create a PR to insert the example into [our Docker datasource docs](https://docs.renovatebot.com/modules/datasource/#docker-datasource). 😉

**Comment by viceice** [comment]
> Maintainers, can you give me the example of how you've setup the `renovate/renovate` image with the correct metadata?
> 
> I can then create a PR to insert the example into [our Docker datasource docs](https://docs.renovatebot.com/modules/datasource/#docker-datasource). 😉

https://github.com/renovatebot/docker-renovate/blob/main/Dockerfile#L9 😉
