### ISSUE TITLE
Update to Jest `v28`

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#15353]
### Describe the proposed change(s).

We should update Jest from `v27` to `v28`, as it has lots of nice features. 🥳 

## Benefits of `v28`

- Sharding of test runs #14572
- `package.json` `exports`
- Fake timers
- GitHub Action reporter that shows the test failure inline with the code
- Better ESM support

## Requirements

- TypeScript version `4.3` or above
- Node versions `12.13`, `14.15`, `16.10` and above

## Todo:

- [x] Other Jest plugins we use support Jest `v28`
- [x] Follow [Guide to upgrade from `v27` to `v28`](https://jestjs.io/docs/upgrading-to-jest28)
- [x] Use [GitHub Action reporter](https://jestjs.io/blog/2022/04/25/jest-28#github-actions-reporter), see PR #16109

## Jest blog post

For more information and all the breaking changes read the [Jest 28 blog post](https://jestjs.io/blog/2022/04/25/jest-28).

**Comment by viceice** [comment]
good sample for shards and codecov

- https://github.com/microsoft/accessibility-insights-web/pull/5343

**Comment by viceice** [comment]
- blocked by https://github.com/kulshekhar/ts-jest/issues/3453

**Comment by HonkingGoose** [comment]
We'll need to upgrade `ts-jest` to `v28.0.0`, or higher, to get Jest 28 support.

I don't know why `ts-jest` doesn't show up on our Dependency Dashboard, maybe it's part of a group?

[`ts-jest` changelog](https://github.com/kulshekhar/ts-jest/blob/main/CHANGELOG.md)

**Comment by rarkins** [comment]
```
DEBUG: Dependency ts-jest is part of group jest monorepo

          {
            "depType": "devDependencies",
            "depName": "ts-jest",
            "currentValue": "27.1.4",
            "datasource": "npm",
            "prettyDepType": "devDependency",
            "lockedVersion": "27.1.4",
            "depIndex": 159,
            "warnings": [],
            "versioning": "npm",
            "sourceUrl": "https://github.com/kulshekhar/ts-jest",
            "homepage": "https://kulshekhar.github.io/ts-jest",
            "currentVersion": "27.1.4",
            "isSingleVersion": true,
            "fixedVersion": "27.1.4",
            "updates": [
              {
                "bucket": "major",
                "newVersion": "28.0.2",
                "newValue": "28.0.2",
                "releaseTimestamp": "2022-05-08T07:47:18.625Z",
                "newMajor": 28,
                "newMinor": 0,
                "updateType": "major",
                "pendingChecks": true,
                "branchName": "renovate/major-jest-monorepo"
              }
            ]
          },
```

**Comment by viceice** [comment]
We should wait for 28.0.2 because of a bad bug which maybe hit us

https://github.com/kulshekhar/ts-jest/blob/main/CHANGELOG.md#2802-2022-05-07

**Comment by HonkingGoose** [comment]
> We should wait for 28.0.2 because of a bad bug which maybe hit us
> 
> https://github.com/kulshekhar/ts-jest/blob/main/CHANGELOG.md#2802-2022-05-07

`ts-jest` is at version `28.0.4` now, that should be good to go?
