### ISSUE TITLE
Explain how to debug Renovate from the CLI

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#15446]
### Describe the proposed change(s).

We should have a page or section in the development docs that explains how to debug Renovate locally from the CLI.

Quote from https://github.com/renovatebot/renovate/issues/15323#issuecomment-1112060074:

> > The key thing we need to do is be able to reproduce it locally using the CLI. Has anyone been able to do that?
> 
> FWIW - I didn't even know this was an option. A readme note on this topic with the right command to run would be great, happy to do it for future issues.
> 
> Thanks!

### Todos:

- [ ] Check if we already have an explanation about debugging Renovate locally from the CLI
- [ ] Create a new section if needed and put it somewhere appropriate
  - [ ] Explain what CLI commands to use

**Comment by Chili-Man** [comment]
This would be great if there was documentation on how to run renovate locally in dry mode so we can see how the config changes would react

**Comment by rarkins** [comment]
Renovate already has a documented dry run mode

**Comment by Chili-Man** [comment]
@rarkins it took me way to long to discover this option hidden deep int the documentation, https://docs.renovatebot.com/modules/platform/local/ ; I think discoverability of it could be better and if mentioned earlier in the docs

**Comment by jamietanna** [comment]
Related: https://github.com/renovatebot/renovate/discussions/41753
