### ISSUE TITLE
Deprecate nested presets

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#15464]
### Describe the proposed change(s).

Deprecate nested presets in the docs.

Do we want to make code changes to forbid nested presets?

### Todos:

- [ ] Search for hits for `nested` and `nest` in the docs
- [ ] Add admonition that nested presets are deprecated in the relevant places
- [ ] Edit docs where needed to account for the deprecation

### Relevant discussion

See https://github.com/renovatebot/renovate/pull/15396#discussion_r864490668 and below.

`@viceice`:

> I think since we support files and paths for presets, we should deprecate nested presets (docs only note)

`@rarkins`:
> Preferring one preset per file?

`@viceice`:
> yes, would make things easier to explain in docs. 

`@rarkins`:
> Agreed. We use nested ones in our internal though..

**Comment by viceice** [comment]
just deprecation in docs only for now.
