### ISSUE TITLE
Drop real manager tests, move fixtures to `renovate-tests` org

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#15540]
## Problem

60s timeout on Gradle tests: https://github.com/renovatebot/renovate/actions/runs/2293039570

## Proposed solution

Drop all real manager tests.

### Benefits

- Drop Java as test dependency

### Drawbacks

- We should have test repositories to run Renovate against, to verify existing command args

## Todos

- [ ] Move fixtures to a new repository: (`renovate-tests` org maybe?) before removing them from the `renovatebot/renovate` repository
- [ ] Ultimate test: run Renovate against the full test org
- [ ] Add note in the code to test any new code against the new "full test" repository

**Comment by viceice** [comment]
@rarkins 🤔 `renovate-tests` is a user, so use another org?

https://github.com/renovate-tests/
