### ISSUE TITLE
Replace `pretty-quick` with `lint-staged`

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#16043]
### Describe the proposed change(s).

Replace `pretty-quick --staged` with [`okonet/lint-staged`](https://github.com/okonet/lint-staged). Include Prettier and the different linters in the pre-commit hook.

https://github.com/renovatebot/renovate/blob/8d9e3be6f3b73f856a87eee31d4aff8c196ced23/.husky/pre-commit#L4

https://github.com/renovatebot/renovate/blob/8d9e3be6f3b73f856a87eee31d4aff8c196ced23/package.json#L294

**Todo:**

- [x] Install `lint-staged` as dev dependency
- [x] Check where we run `pretty-quick`
- [x] Replace `pretty-quick` commands with `lint-staged` commands
- [x] Run `ls-lint`
- [x] Run `eslint`
- [x] Run `markdown-lint`
- [x] Open PR

**Comment by PhilipAbed** [comment]
- does this `lint-staged` replace `pretty-quick` functionality fully?
- Are you willing to do this or should we do it ?

**Comment by PhilipAbed** [comment]
cool, we'll take it then, thanks!

**Comment by viceice** [comment]
> * does this `lint-staged` replace `pretty-quick` functionality fully?

yes

> * Are you willing to do this or should we do it ?

maybe 🙃

**Comment by prophet1906** [comment]
Hi, I am new to this project and interested in picking this up.
