### ISSUE TITLE
Upstream `@breejs/later` types to DefinitelyTyped project

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#18085]
## Intro

I fixed some typos in the `@breejs/later` type file. [^typo-fix] This file should live somewhere else. The logical place is the DefinitelyTyped project [^DefinitelyTyped], which hosts types for many packages.

A while back @JamieMagee tried upstreaming the file, but this failed for whatever reason. @JamieMagee offered to try upstreaming the file again. ❤️ 

## Todo:

- [ ] Upstream `@breejs/later` types from this file: [`lib/types/later.d.ts`](https://github.com/renovatebot/renovate/blob/main/lib/types/later.d.ts) to DefinitelyTyped [^DefinitelyTyped]
- [ ] Create PR on `renovatebot/renovate` that:
  - [ ] Drops `@breejs/later` types file
  - [ ] Adds a dependency on the upstream `@breejs/later` types package from DefinitelyTyped

[^typo-fix]: https://github.com/renovatebot/renovate/pull/18065  
[^DefinitelyTyped]: https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by JamieMagee** [comment]
Created a new PR upstream: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62566

**Comment by HonkingGoose** [comment]
Hi @JamieMagee 👋 

Your upstream PR got closed by the stale bot. 😞 Do you still want to work on this issue, or do you want to give up?

**Comment by HonkingGoose** [comment]
I'm in half a mind to close this issue as `won't do`, @JamieMagee tried to get this into upstream twice, and each time the maintainers wanted changes to the PRs, and eventually the stale bot closed the PRs.

**Comment by JamieMagee** [comment]
I'd still like to do this, I just don't have capacity right now.

**Comment by JamieMagee** [comment]
Third time's the charm https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65724

**Comment by HonkingGoose** [comment]
@JamieMagee Thank you for upstreaming the types! ❤️🥳
