### ISSUE TITLE
Use generic verbs that work with any input method in docs

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#18504]
### Intro

I tried my hand at changing both the docs and the code, and got stuck on the code part. So I'm splitting this work into two parts:

- #18504
- #19164

I'll do the docs changes myself, and let one of the maintainers fix-up the code.

### Describe the proposed change(s).

I want to change our docs so that we use generic verbs that work with any input method.

The Microsoft style guide has a page that explains "describing interactions with UI": [^quote]

> Customers interact with products using different input methods: keyboard, mouse, touch, voice, and more. So use generic verbs that work with any input method. Don't use input-specific verbs, such as _click_ or _swipe_. Instead, use the verbs listed here.

Their style guide has a table with good verbs, and examples on how to use them in a sentence.

I've searched our repository for some common input verbs:

| Input specific verb | Hits on `main` |
| --- | --- |
| Click | 109 |
| Press | 1 |
| Swipe | No relevant hits |
| Touch | 2 relevant hits |
| Tick | 8 |
| Ticking | 2 |

## Todo in docs:

- [x] Replace `click` and `clicking` with `select`
- [x] Replace `press` and `pressing`
- [x] Replace `swipe`, no hits
- [x] Replace `touch`
- [x] Replace `tick` with `select`
- [x] Replace `ticking` with `selecting`

[^quote]: https://learn.microsoft.com/en-us/style-guide/procedures-instructions/describing-interactions-with-ui

**Comment by rarkins** [comment]
So what instead of click? Mostly refers to checkboxes?

**Comment by HonkingGoose** [comment]
# Replace `click` with `select`

We can replace `click` with `select`. Quote from the guide:

> Instructing the customer to select a specific item, including:
> 
> - Selecting an option, such as a button.
> - Selecting a checkbox.
> - Selecting a value from a list box.
> - Selecting link text to go to a link.
> - Selecting an item on a menu or shortcut menu.
> - Selecting an item from a gallery.
> - Selecting keys and keyboard shortcuts. (Document keyboard shortcuts only if they're the most likely way the customer will accomplish a task or as an alternative input method, usually in a separate keyboard shortcuts article.)

# New wording for selecting checkboxes

Examples of the new wording in the Dependency Dashboard:

> ## Pending Approval
> 
> These branches will be created by Renovate only once you select their checkbox below.
>
> - [ ] Update 1
> - [ ] Update 2

> ## Awaiting Schedule
> 
> These updates are awaiting their schedule. Select a checkbox to get an update now.
> 
> - [ ] Update 1
> - [ ] Update 2

> ## Pending Status Checks
> 
> These updates await pending status checks. To force their creation now, select the checkbox below.
>
> - [ ] Update 1
> - [ ] Update 2

>  --------
>  - [ ] Select this box to trigger a request for Renovate to run again on this repository
