### ISSUE TITLE
Use generic verbs that work with any input method in code

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#19164]
### Intro

I tried my hand at changing both the docs and the code, and got stuck on the code part. So I'm splitting this work into two parts:

- #18504
- Current issue

I'll do the docs changes myself, and let one of the maintainers fix-up the code. That way I don't have to worry about breaking production code. 😄 

### Describe the proposed change(s).

We should change our code so that we use generic verbs that work with any input method.

The Microsoft style guide has a page that explains "describing interactions with UI": [^quote]

> Customers interact with products using different input methods: keyboard, mouse, touch, voice, and more. So use generic verbs that work with any input method. Don't use input-specific verbs, such as _click_ or _swipe_. Instead, use the verbs listed here.

Their style guide has a table with good verbs, and examples on how to use them in a sentence.

I've searched our repository for some common input verbs:

| Input specific verb | Hits on `main` |
| --- | --- |
| Click | 109 |
| Press | 1 |
| Swipe | No relevant hits |
| Touch | 2 relevant hits |
| Tick | 8 |
| Ticking | 2 |

## Todo in code files:

- [ ] Replace `click` and `clicking`
- [ ] Replace `press` and `pressing`
- [ ] Replace `swipe`, no hits
- [ ] Replace `touch`
- [ ] Replace `tick` with `select`
- [ ] Replace `ticking` with `selecting`
- [ ] Replace `select/click this box` with `select this checkbox` 

[^quote]: https://learn.microsoft.com/en-us/style-guide/procedures-instructions/describing-interactions-with-ui
