### ISSUE TITLE
Sort A-Z for more presets and enforce with ESLint rule

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#19171]
## Background

This is basically a follow-up issue after this one:

- #18938 

Sort presets from A-Z and enforce the ordering with this ESLint rule:

```typescript
/* eslint sort-keys: ["error", "asc", {caseSensitive: false, natural: true}] */
```

When the source files are sorted properly it also makes the lists of presets in our docs sorted. This helps when users are browsing the presets via our docs.

## Add snapshot tests on `main` branch first

We should add snapshot tests on `main` first to capture the current state, like this:

- https://github.com/renovatebot/renovate/commit/4abd0abea82a8880a91c2e3c4e1216ffbc8459c6

## Todo list

- [ ] Add snapshot tests for current presets state on `main`
- [ ] Sort presets in these files
  - [ ] `lib/config/presets/internal/compatibility.ts`
  - [ ] `lib/config/presets/internal/config.ts`
  - [x] `lib/config/presets/internal/default.ts`
  - [ ] `lib/config/presets/internal/docker.ts`
  - [ ] `lib/config/presets/internal/group.ts`
  - [ ] `lib/config/presets/internal/helpers.ts`
  - [ ] `lib/config/presets/internal/index.ts`
  - [ ] `lib/config/presets/internal/monorepo.ts` -> the `patternGroups` object should be sorted A-Z
  - [ ] `lib/config/presets/internal/npm.ts` -> this one is easy 😉 
  - [ ] `lib/config/presets/internal/packages.ts`
  - [ ] `lib/config/presets/internal/preview.ts`
  - [ ] `lib/config/presets/internal/regex-managers.ts` -> this one is also easy 😉 
  - [x] `lib/config/presets/internal/replacements.ts`
  - [ ] `lib/config/presets/internal/schedule.ts`
  - [ ] `lib/config/presets/internal/workarounds.ts`
  
## Example PR: 

- #19003

**Comment by weikangchia** [comment]
Hi @HonkingGoose , I can help out with this issue 😀

**Comment by HonkingGoose** [comment]
@weikangchia Thank you very much for fixing this issue! ❤️

**Comment by weikangchia** [comment]
@HonkingGoose , thanks for the opportunity to learn and work on this project too!
