### ISSUE TITLE
Rename `migratePresets` to `remapPresets`

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#19291]
### Describe the proposed change(s).

Comment from @rarkins: [^comment]

> So I think ideally it would have been called something like "remapPresets" because it doesn't migrate anything itself per se. But now that we have it, is it work renaming it?

### Todo

- [ ] Make changes in code to rename `migratePresets` to `remapPresets`
- [ ] Add config migration for the old `migratePresets` config option
- [ ] Update docs references to `migratePreset` to `remapPresets`

[^comment]: https://github.com/renovatebot/renovate/issues/16605?notification_referrer_id=NT_kwDOAhTO8bM0MDA2MjYxNTE1OjM0OTE4MTI5#issuecomment-1186221742
