### ISSUE TITLE
Explain how to get GitHub's pull request merge queue working with Renovate

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#20321]
### What would you like Renovate to be able to do?

Copy/pasting @rarkins mission statement: [^statement]

> Something that means multiple PRs don't need to be rebased after each merge.

[^statement]: https://github.com/renovatebot/renovate/issues/6011#issue-603228248

#### Partially working already [^quote]

> Actually, Renovate can already add to GitHub merge queues. It is necessary to enable auto merge in GitHub's repo settings (even though a merge queue is being used). Renovate is already making the right API call:
> 
> https://github.com/renovatebot/renovate/blob/bde951257a79737351859d1c08db0ad214e61494/lib/modules/platform/github/index.ts#L1455-L1458
> 
> So it ends up looking like so:
> 
> <img alt="github renovate" width="350" src="https://user-images.githubusercontent.com/38842733/217890493-a26b30c2-fa73-4063-98de-6514257326f7.jpeg">
> 
> This is using platform auto merge:
> 
> ```json
> {
>     "automerge": true,
>     "automergeType": "pr",
>     "platformAutomerge": true
> }
> ```

#### Who can use Merge Queues?

> Pull request merge queues are available in any public repository owned by an organization, or in private repositories owned by organizations using GitHub Enterprise Cloud. [^docs]

[^docs]: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
[^quote]: https://github.com/renovatebot/renovate/issues/6011#issuecomment-1424561440

#### Relevant documentation:

- [GitHub Docs, Merge Queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue)
- [GitHub Docs, `merge_group` webhook/event](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#merge_group)
- [GitHub Docs, `merge_group` explanation for end-users](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group)
- [GitHub Blog about `merge_group`](https://github.blog/changelog/2022-08-18-merge-group-webhook-event-and-github-actions-workflow-trigger/)

#### Todos

- [x] Explain current support for GitHub Merge Queue in our docs
- [x] Discover what works/doesn't work right now
- [x] Make todo list to get the feature working fully

### Is this a feature you are interested in implementing yourself?

No

**Comment by xUnholy** [comment]
I tried using the above example to add my PR to the auto-merge queue however, it did not seem to work, worth noting I'm using a self-hosted GHA renovate and it's currently on the latest version.

**Comment by vchernin** [comment]
> I tried using the above example to add my PR to the auto-merge queue however, it did not seem to work, worth noting I'm using a self-hosted GHA renovate and it's currently on the latest version.

I used the GitHub hosted renovate instance for my test. Can you confirm auto merge is enabled in GitHub's repo settings, and the merge queue is being enforced for the base branch renovate is active on? Does auto merge work without the merge queue?

**Comment by xUnholy** [comment]
I saw this in the logs with the above settings you mentioned. We have set merge queue as default, and have a GHA that approves the PRs when the PR is created itself. If Renovated added the PR to the merge queue the approval would then trigger the merge.

<img width="953" alt="Screenshot 2023-02-15 at 4 08 19 pm" src="https://user-images.githubusercontent.com/20387402/218937483-1c6d8076-88fd-4736-9653-424474c4c771.png">

Error:

```
 INFO: All merge attempts failed (repository=<REDACTED>/<REDACTED>, branch=renovate/renovatebot-github-action-34.x)
       "pr": 1325
```

**Comment by vchernin** [comment]
Do you see logs about GitHub-native automerge? I don't see logs about merge attempts failing, my setup seems to try to automerge and nothing else.

```
DEBUG: GitHub-native automerge: success...PrNo: 222(branch="renovate/docker.io-caddy-2.6.3-builder-alpine")
INFO: PR created(branch="renovate/docker.io-caddy-2.6.3-builder-alpine")
{
  "pr": 222,
  "prTitle": "chore(deps): update docker.io/caddy:2.6.3-builder-alpine docker digest to cd3e4f9"
}
(...)
DEBUG: Skipping assignees and reviewers as automerge=true(branch="renovate/docker.io-caddy-2.6.3-builder-alpine")
DEBUG: Created Pull Request #222(branch="renovate/docker.io-caddy-2.6.3-builder-alpine")
DEBUG: PR is configured for automerge(branch="renovate/docker.io-caddy-2.6.3-builder-alpine")
```

**Comment by HonkingGoose** [comment]
Maybe you need to add `merge_group` event in your GitHub Action files to get the merge queue working? Quote from the GitHub Docs [^quote]

> ### Triggering merge group checks with GitHub Actions
> 
> You can use the `merge_group` event to trigger your GitHub Actions workflow when a pull request is added to a merge queue. Note that this is a different event from the `pull_request` and `push` events.
> 
> A workflow that reports a check which is required by the target branch's protections would look like this:
> 
> ```yaml
> on:
>   pull_request:
>   merge_group:
> ```
> 
> For more information see "[Events that trigger workflows](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge-group)"

[^quote]: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions

**Comment by HonkingGoose** [comment]
Renovate can already put it's PRs in the GitHub Merge Queue, at least with our configuration, see this message template:

> Merged via the queue into `main` with commit `xxxyyy` x hours ago

For example:

- https://github.com/renovatebot/renovate/pull/20446

We probably only need to document how users can get Merge Queue working with Renovate. As far as I understand you need to:

1. Update your GitHub Action CI files so they run on the `merge_group` event.
1. If you use some other CI provider: allow tests to run on the temporary `gh-readonly-queue/{base_branch}` prefix.
1. Enable branch protection setting "Require merge queue" for the base branch.
1. Confirm if your "required checks" are correct.
1. Allow Renovate to automerge with:
    ```json
    {
        "automerge": true,
        "platformAutomerge": true
    }
    ```
    
I think a good place for this information is the [Key concepts page for Automerge](https://docs.renovatebot.com/key-concepts/automerge/). We should also link to the main [GitHub Docs for Merge Queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) as well.

**Comment by mbrevda** [comment]
Is 1. relevant when using the Github App? (i.e. not self hosted and not using a github action)

**Comment by HonkingGoose** [comment]
> Is 1. relevant when using the Github App? (i.e. not self hosted and not using a github action)

If you're using Renovate's GitHub app, and don't use GitHub Actions, you can skip step 1, but must follow step 2 of my list.

Here's the relevant quote from the GitHub Merge Queue docs: [^quote]

> ### Triggering merge group checks with other CI providers
> 
> With other CI providers, you may need to update your CI configuration to run when a branch that begins with the special prefix `gh-readonly-queue/{base_branch}` is created.

[^quote]: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-other-ci-providers
