### ISSUE TITLE
v36 planning

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#21134]
### Describe the proposed change(s).

- [ ] #9229
  - [ ] renovatebot/docker-renovate#249 
  - [ ] renovatebot/docker-renovate#1207
  - [ ] renovatebot/docker-renovate-full#1558
- [x] #10097
- [x] #12024
  - [x] #21136
- [x] #12062
  - [x]  #20930
- [x] #12532 
  - [x] #21122
- [x] #13953
  - [x] #16534
- [ ] #18811
- [x] #20926
  - [x] #22703
- [x] #21217
  - [x] #22708
- [x] #21318
- [x] #21319
  - [x] #21327
- [x] #21320
  - [x] #21326
- [ ] Use global mode on full docker image
  - [ ] renovatebot/docker-renovate-full#1599
- [ ] Set slim image to latest and tag fat image with `-full` suffix
  - [ ] renovatebot/docker-renovate#1237
- [x] Drop node v19 support

**Comment by JamieMagee** [comment]
What do you think about enabling `osvVulnerabilityAlerts` by default? It's been in Renovate since v34  and feedback in https://github.com/renovatebot/renovate/discussions/20542 is positive.

**Comment by rarkins** [comment]
But how about with GitHub which already has alerts built in? I'm not site it's been robustly tested

**Comment by JamieMagee** [comment]
Yeah, I should have been more explicit that I meant enabling it everywhere except on GitHub. I had mentioned it in the original PR, but I can't find the comment now.
