### ISSUE TITLE
Try Vitest test runner on this repository

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#21301]
### Describe the proposed change(s).

I think we want to try the Vitest test runner, to see if it's faster then Jest? I've created this issue to discuss things, and so I can link to other relevant issues.

Vitest says that: [^quote]

> Vitest has been designed with a Jest compatible API, in order to make the migration from Jest as simple as possible. Despite those efforts, you may still run into the following differences:

#### Todos to migrate to Vitest

These todos come from the [Vitest guide to migrate from Jest](https://vitest.dev/guide/migration.html):

- [ ] Keep the globals API from Jest with the `globals` configuration setting **or** update code to use `imports` from the `vitest` module instead
- [ ] Module mocks
- [ ] Auto-mocking behavior
- [ ] Importing the original of a mocked package
- [ ] Jasmine API
- [ ] Envs
- [ ] Done Callback
- [ ] `beforeAll`/`beforeEach` hooks
- [ ] Types
- [ ] Timers (Vitest doesn't support Jest's legacy timers)
- [ ] Vue Snapshots (we probably don't use any?)

#### Discussion

Some things to think about:

- Vitest is not stable, the current release is `0.29.8`.
- Vitest supports running consecutive tests in parallel. [^concurrent-tests]
- Supports native code coverage via `c8` (default) and instrumental code coverage via `istanbul` [^coverage]
- Read Vitest's test runner comparison page [^comparison]

#### Related issues:

- #20477
- #14572

[^quote]: https://vitest.dev/guide/migration.html#migrating-from-jest
[^concurrent-tests]: https://vitest.dev/guide/features.html#running-tests-concurrently
[^coverage]: https://vitest.dev/guide/coverage.html
[^comparison]: https://vitest.dev/guide/comparisons.html

**Comment by HonkingGoose** [comment]
@zharinov sped up the tests massively. 🥳 My latest docs PR got automerged by GitHub via Merge Queue in about 10 minutes, compared to about 25 minutes before the changes. 😱 

Do the maintainers still want to try Vitest, or are we happy with our current test speed?

**Comment by viceice** [comment]
yes, would like to try it.

**Comment by viceice** [comment]
i think I've not enough time to make it alone 🙃

**Comment by RahulGautamSingh** [comment]
> i think I've not enough time to make it alone 🙃

I would be happy to contribute here too☺

**Comment by viceice** [comment]
not sure about the best way to start. does vitest have something like the jest.mock functions? so we can try to create some compabillity stuff?
