### ISSUE TITLE
Put our Renovate's org regex managers into public regex manager presets

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#22025]
### Intro

`@rarkins` said in PR #21239 that:

> We should probably convert our regex managers into presets but not sure there's any point including them by default

> We should check if any of our org's regex managers are not in these presets

### Summary

| Repository | Put into regex manager preset? [^docs] |
| :---------- | :------------------ | 
| `helm-charts` | Probably yes [^helm-charts] |
| `.github` | Probably yes [^.github] |
| `github-action` | Maybe, needs to be generalized [^github-action] |
| `pre-commit-hooks` | Maybe [^pre-commit-hooks] |
| `docker-renovate` | No |
| `renovatebot.github.io` | No |
| `docker-renovate-full` | No | 
| `ruby-semver` | No |
| `osv-offline` | No |
| `azure-devops-marketplace` | No |
| `pep440` | No |
| `renovate-approve-bot-bitbucket-cloud` | No |
| `renovate-approve-bot` | No |
| `tutorial` | No |
| `eslint-plugin` | No |
| `renovate` | No | 
| `docker-node-docker` | No |

### Todo

- [x] Summarize findings in table
- [ ] Review my findings and determine if we need to create new presets
- [ ] Create PR which puts new regex manager presets in code

[^docs]: [Regex Manager Presets docs](https://docs.renovatebot.com/presets-regexManagers/)
[^github-action]: [`github-action` renovate config](https://github.com/renovatebot/github-action/blob/main/.github/renovate.json)
[^pre-commit-hooks]: [`pre-commit-hooks` renovate config](https://github.com/renovatebot/pre-commit-hooks/blob/main/renovate.json)
[^helm-charts]: [`helm-charts` renovate config](https://github.com/renovatebot/helm-charts/blob/main/renovate.json)
[^.github]: [`.github` renovate config](https://github.com/renovatebot/.github/blob/main/default.json)

**Comment by HonkingGoose** [comment]
I found another cool regexManager that we could put into two new presets. Snippet from our `renovatebot/.github/default.json` file: [^renovate-custom-regex-manager]

```json
    {
      "description": "Update Github Action references in the Markdown files",
      "fileMatch": ["\\.md$"],
      "matchStrings": [
        "\\suses: (?<depName>[\\w-]+/[\\w-]+)(?<path>/.*)?@(?<currentValue>v\\d+\\.\\d+\\.\\d+)",
        "\\suses: (?<depName>[\\w-]+/[\\w-]+)(?<path>/.*)?@(?<currentDigest>[a-z0-9]{40}|[a-z0-9]{64}) # tag=(?<currentValue>v\\d+\\.\\d+\\.\\d+)"
      ],
      "datasourceTemplate": "github-tags",
      "versioningTemplate": "semver"
    },
```

I don't know if the code above code actually works right now. If I remember right sometimes Renovate doesn't update the Markdown files properly for some reason...

Proposed names for the presets:

- `regexManagers:updateGitHubActionReferencesInAllMarkdownFiles`
- `regexManagers:updateGitHubActionReferencesInMarkdownReadme`

### How the new presets can help

Here's a random `readme.md` file from a project. The readme lists `actions/checkout@v2`, but the current version is `@v3`. [^quote]

> # Report updated dependencies
> 
> This Github Actions runs on changes to PR requests to detect and report changes made to dependencies.
> Dependency lookups, change detections and fetching of release notes are all done by [Renovate Bot](https://github.com/renovatebot/renovate)
> 
> ```yml
> name: 'build-test'
> on:
>   pull_request:
> 
> jobs:
>   report-updated-dependencies:
>     runs-on: ubuntu-latest
>     steps:
>       - uses: actions/checkout@v2
>       - uses: AurorNZ/report-updated-dependencies@v1
> ```

The project above uses Dependabot to update their dependencies, while the Action is meant for Renovate. If they switched to Renovate for their own project, they could write a RegexManager to update their `README.md` file automatically, or use one of the new presets. 😄 

[^renovate-custom-regex-manager]: https://github.com/renovatebot/.github/blob/46e399fb8f362ed92a1bb76be372e0f9c0071a3a/default.json#L137-L146

[^quote]: https://github.com/AurorNZ/report-updated-dependencies/blob/aa7addd6f1d33d576834c77c8d01ec1102a07abd/README.md
