### ISSUE TITLE
Remove `status:ready` label from repository, workflows, forms, and docs

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#24983]
### Describe the proposed change(s).

If a user creates an Issue, it's automatically converted to a Discussion. The bug/feature is discussed, and when we have the requirements figured out, a maintainer creates a issue. This means that (in theory, at least) we should only have `status:ready` issues. This means that we can drop the `status:ready` label.

#### What about the other `status:*` labels?

We _keep_ the `status:requirements` label in case we need to "cheat" to create Issues we know we need, but don't have the requiements figure out fully. This should be seen as an "escape hatch" though.

We _keep_ the `status:blocked` label, to indicate issues that need some other thing first.

And finally, we also _keep_ the `status:in-progress` label to indicate that we started work on the issue.

## Todos:

- [x] Drop `status:ready` mentions from developer docs
- [x] Explain in developer docs that we should only create "issues that are actionable", if we don't already
- [x] Drop `status:ready` from Issue Forms, Discussion Forms
- [x] Drop `status:ready` from any bot/workflow configuration
- [ ] Check if everything keeps working
- [ ] Final stap: remove the actual `status:ready` label in the GitHub UI
