### ISSUE TITLE
Sort `packageRules` in docs, validate with tests

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#29703]
### Describe the proposed change(s).

`@rarkins` wants to move the `packageRules` docs to a new page in the docs. Making that move is a big change, with a lot of links to update. To make the move easier, we should refactor and test the current `packageRules` docs first.

**Todos:**

- [x]  Write test to check if current `packageRules` entries are in the right order, test fails, because the list is not properly sorted right now.
- [x] Move `packageRules` items into correct order, test passes now.
- [ ] Merge the refactoring PR

Once these todos are done, we can start work on this issue:

- #29704
