### ISSUE TITLE
List datasources with `releaseTimestamp` field in `minimumReleaseAge` docs

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#30714]
#### Summary

Autogenerate a list of datasources with timestamps in the `minimumReleaseAge` docs, under a new sub-heading.

#### Todos:

- [ ] Write new code for our docs generating script(s) to:
  - [ ] Fetch all datasources with `releaseTimestamp` field
  - [ ] Create list of all datasources
  - [ ] Create new sub-heading under the `minimumReleaseAge` heading, title `Datasources with timestamp`
