### ISSUE TITLE
Print package manager version as part of regular debug logging of child process `stdout`

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#30824]
## Summary

For each package manager listed below: print the version of the package manager as part of regular debug logging of child process `stdout`.

As an example: before Renovate uses `npm` it should print the output of `npm --version` into the logs.

### Todos:

- [ ] Print for `bun`
- [ ] Print for `bundler`
- [ ] Print for `cocoapods`
- [ ] Print for `composer`
- [ ] Print for `copier`
- [ ] Print for `corepack`
- [ ] Print for `dotnet`
- [ ] Print for `erlang`
- [ ] Print for `elixir`
- [ ] Print for `flux`
- [ ] Print for `gleam`
- [ ] Print for `golang`
- [ ] Print for `gradle`
- [ ] Print for `hashin`
- [ ] Print for `helm`
- [ ] Print for `helmfile`
- [ ] Print for `java`
- [ ] Print for `java-maven` (if Renovate uses it?)
- [ ] Print for `jb` (jsonnet-bundler)
- [ ] Print for `kustomize`
- [ ] Print for `maven`
- [ ] Print for `nix`
- [ ] Print for `node`
- [ ] Print for `npm`
- [ ] Print for `pdm`
- [ ] Print for `php`
- [ ] Print for `pip-tools`
- [ ] Print for `pipenv`
- [ ] Print for `pnpm`
- [ ] Print for `poetry`
- [ ] Print for `python`
- [ ] Print for `ruby`
- [ ] Print for `rust` (Stand-alone command: `cargo version`, or with flag: `cargo --version`)
- [ ] Print for `yarn`
- [ ] Print for `yarn-slim`
- [ ] Print for `dart`
- [ ] Print for `flutter`
- [ ] Print for `vendir`
