### ISSUE TITLE
CLI: eratic / non-deterministic behavior 

### ISSUE THREAD

**Issue by bagage** [renovatebot/renovate#3178]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
Depending on the option you provide, renovate enables (or not) options. But it seems there are no CLI validator anywhere, so user may type wrong things without being warned.

Among others:

- [ ] choice option (has to be chosen from a fixed choices list): this list is not displayed and you have to guess the possible values (for instance `binarySource` before #3138). For instance, you can type `--binarySource=foobar` and renovate will just run smoothly (same thing for `--log-level foo`). **update: not supported upstream yet: https://github.com/tj/commander.js/issues/467**
- [x] boolean option: most of CLI allows boolean option to be passed directly, eg `git commit --allow-empty`, while renovate actually expects `true` parameter to be passed: `node lib/renovate.js --require-config=true`. Again, if you type simply `--require-config` or `--require-config=yes`… renovate will run but just ignore your input. Not nice. #3356 
- [x] cannot show you an example, but sometime renovate tells you `no repository found, maybe use --autodiscover`, while the repository is being passed in. I often add `--log-level foo` to bypass this. (related to #3356)
- [ ] order: ~~the hardest to debug, but sometime renovate ignores your input, for instance: `node ../renovate/lib/renovate.js --help --token xxx bagage/gradle-template` will **NOT** display the help and just run without it…~~ `node lib/renovate.js  --help --git-fs ssh myrepo/user` should display help, but it actually does not. As soon as you provide a repository, `--help` is never displayed.

I do not know if a library is used to handle the CLI, but it's really hard to use it right now with these issues. 
An extra bonus would be CLI completions too.

**Comment by rarkins** [comment]
If you always use `--option=true` instead of `--option` and `--option=x` instead of `--option x`. i.e. don't rely on implicit `true` and use an equals instead of space.

**Comment by rarkins** [comment]
FYI we use https://github.com/tj/commander.js for CLI parsing and our code is here: https://github.com/renovatebot/renovate/blob/master/lib/config/cli.js

> * cannot show you an example, but sometime renovate tells you `no repository found, maybe use --autodiscover`, while the repository is being passed in.

This probably happened if you had a boolean option immediately before the repo name. e.g. you ran `yarn start --include-forks abc/def` instead of `yarn start --include-forks=true abc/def`.

**Comment by mastermatt** [comment]
@rarkins is this considered a bug? 
I found this related issue when I was about to create one for using `--force-cli` after `--endpoint` (which errors out).

**Comment by rarkins** [comment]
Nothing I’ve seen so far is a bug IMO but if someone wants to propose a different third party library to use, I’m open to the idea. 

In short, always use `—key=value` and I don’t think you’ll get any ambiguous behaviour.

**Comment by bagage** [comment]
I've quickly looked at commander and maybe boolean flags (`--force-cli`, etc.) could be handled better (eg without having to provide `true` as value). But I did not investigate more yet the problem on my side.

**Comment by bagage** [comment]
SO I've quickly looked at the different issues and:

- I've fixed boolean issues (eg now `--require-config` and `--require-config true` are both valid and equivalent, while `--require-config false` also work. `--require-config foo` will raise an exception because foo is not a valid boolean value).
 - Select/choice values is not supported yet in commander so we cannot deal with it now
- I could not address the remaining issue about `--help` not being displayed sometime…
