### ISSUE TITLE
Apply new Mend styling to the Renovate docs assets

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#32766]
## Summary

Mend now has a new look, which the repository readme already uses. But the Renovate docs still use _old_ assets.

Here's our current landing page for the docs. Note the _old_ favicon and _old_ banner image:

![Renovate docs landing page with old favicon and old banner image](https://github.com/user-attachments/assets/7f11edaa-c85e-423a-97cc-afa1566d8f75)

### Todos:

- [ ] Update the [`logo.png` image of the Mend paintbrush](https://github.com/renovatebot/renovate/blob/main/docs/usage/assets/images/logo.png)
- [ ] Update the favicon source image, if needed. (Maybe the favicon is auto-generated based on the `logo.png` from above?)
- [ ] Update the link in the landing page document [`docs/usage/index.md`](https://github.com/renovatebot/renovate/blob/main/docs/usage/index.md) to point to a new-style Mend banner image.

### Put new Mend banner into open-source repo?

Should we put the _new_ Mend banner into the `renovatebot/renovate` repository? Or is there some license problem with putting a "proprietary" asset into the open-source repository? Maybe that's why the old banner image is hosted on a Mend-controlled domain?

I'm asking because it would be easier to have the asset in the repository. That way it's easier to find and update later.
