### ISSUE TITLE
Upstream typescript definitions

### ISSUE THREAD

**Issue by JamieMagee** [renovatebot/renovate#4528]
**What would you like Renovate to be able to do?**
Currently we [maintain typescript definitions for several packages](https://github.com/renovatebot/renovate/tree/master/lib/types). It would be nice if we could upstream those—either to the dependency itself, otherwise to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

**Describe the solution you'd like**
I'll create the relevant PRs and track their progress here

**Describe alternatives you've considered**

**Additional context**
- [x] clean-git-ref #5223 
  - [x] DefinitelyTyped/DefinitelyTyped#41854
  - [ ] ~TheSavior/clean-git-ref#32~ (Unmaintained. We should copy this into our codebase)
- [x] github-url-from-git #4541
  - [x] DefinitelyTyped/DefinitelyTyped#38576 
  - [ ] ~tj/node-github-url-from-git#24~ (Unlikely to be merged)
- [x] re2 #4537 
  - [x] DefinitelyTyped/DefinitelyTyped#38538
  - [x] uhop/node-re2#52
- [x] semver-stable #5212 
  - [x] DefinitelyTyped/DefinitelyTyped#41756
  - [ ] kaelzhang/node-semver-stable#
- [x] semver-utils #5204 
  - [x] DefinitelyTyped/DefinitelyTyped#41734
  - [ ] https://git.coolaj86.com/coolaj86/semver-utils.js
- [x] yawn-yaml #5161 
  - [x] DefinitelyTyped/DefinitelyTyped#41627
  - [ ] ~mohsen1/yawn-yaml#27~ (Unlikely to be merged)
- [x] global-agent #5224 
  - [x] DefinitelyTyped/DefinitelyTyped#41855
  - [ ] gajus/global-agent#

**Comment by ChristianMurphy** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38576

**Comment by JamieMagee** [comment]
I'm considering this closed, as all the types are now available in Definitely typed. Some follow-up work around getting the libraries themselves to maintain the definitions, but I'll not hold this issue open for that.
