### ISSUE TITLE
Meta: move semantic-release from circle to actions

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#5514]
Let's move releasing to Actions and then deprecate CircleCI use.

- [x] Define npm release token in Actions secrets (the embedded GitHub token in Actions should be enough for the GitHub part)
- [ ] Add semantic releasing to Node 12 on Linux in Actions
- [ ] Disable releasing on CircleCI

Note: I don't want to use any third party action for this, because of the risk of it stealing credentials.

**Comment by rarkins** [comment]
Ref: https://github.com/semantic-release/semantic-release/issues/974

**Comment by rarkins** [comment]
`NPM_TOKEN` added to secrets

**Comment by rarkins** [comment]
I'm trying to work out where this fits in to our actions currently:

We want it to only run once, e.g. on Node 12 on Linux only

We want it to run on `master` branch only (although `semantic-release` should be smart enough to skip if it's run on an alternative branch).

We want it to run only after build and test is completed.

**Comment by ViceIce** [comment]
then we need to add a new `release`  job to `test.yml` which depends on `test` job.

we can add
`if: github.ref == 'refs/heads/master'` to the new job to only execute on master and save a worker

**Comment by rarkins** [comment]
If it's a new job, does it execute within a new container and hence needs checkout + install + build first?

**Comment by ViceIce** [comment]
jepp

```yml
  release:
    name: release
    needs: test
    runs-on: ubuntu-latest

    # tests shouldn't nee more than 10 min
    timeout-minutes: 15
  

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Init platform
        id: init
        shell: bash
        run: |
          echo "::set-output name=yarn_cache::$(yarn cache dir)"
          git config --global core.autocrlf false
          git config --global core.symlinks true
          git config --global user.email 'bot@renovateapp.com'
          git config --global user.name  'Renovate Bot'
          node --version
          yarn --version

      - uses: actions/checkout@v2

      - name: Cache Yarn packages
        id: yarn_cache_packages
        uses: actions/cache@v1
        with:
          path: ${{ steps.init.outputs.yarn_cache }}
          key: v1-${{ runner.os }}-yarn_cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            v1-${{ runner.os }}-yarn_cache-

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-yarn-
            
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn semantic-release
      - run: curl -X POST -d '{}' $NETLIFY_DEPLOY_WEBHOOK
```

**Comment by ViceIce** [comment]
ok, env vars needs to be added from secrets

**Comment by ViceIce** [comment]
added condition to job above

**Comment by rarkins** [comment]
https://github.community/t5/GitHub-Actions/Is-there-a-way-to-depend-on-actions-from-another-file/td-p/35237

Wondering if we want to use GitHub's native "release" concept (which never seemed to get much use from anyone, but maybe actions will change that)
