### ISSUE TITLE
Style issues with documentation

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#7626]
**What Renovate type, platform and version are you using?**

Problem is with the documentation files.

**Describe the bug**

I noticed there are some style issues with the current docs:

- [ ] Overly long sentences, and run-on sentences.
- [ ] Examples that don't really clarify things due to unclear sentence structure.
- [ ] Some broken English sentences.
- [ ] Too much use of `Therefore`.
- [ ] I've counted at least 3 ways we say "the next part is an example": `e.g.`, `for example`, and `i.e.`. @rarkins said that `e.g.` is probably best in most situations.
- [ ] There are some complex "if" statements.
- [ ] Most of the docs use the passive voice instead of the clearer active voice.
- [ ] No consistent style or tone of voice.
- [x] Inconsistent use of `.` to mark the end of a list item. (See issue #7666)
- [ ] Inconsistent spelling (**rarkins** decided we should use US spelling).

Now I know this is a lot of things at once, but these are the things that jumped out at me when I was doing the work to refactor the docs to use the "one sentence per line" pattern.

**Relevant debug logs**

**To Reproduce**

Look trough the current documentation.

**Additional context**

I'm opening this issue as a catch-all issue, so that we can discuss which items the Renovate team cares about.
I'm of course willing to help by creating smaller issues, and then opening pull request to fix each issue.
But I need to know before I start which issues you care about and which you don't care about.

## Checklist for @HonkingGoose's use:

**`docs/development` files**:

- [x] `adding-a-package-manager.md` (#7704)
- [x] `branches-commits.md` (#7706)
- [x] `configuration.md` (#7707)
- [x] `design-decisions.md` (#7709)
- [x] `issue-labeling.md` (Skipping because I made this file, and it was reviewed already by the Renovate team.)
- [x] `local-development.md` (#7710)
- [x] `readme.md` (#7711)
- [x] `shareable-configs.md` (#7722)

---

**`docs/usage/modules` files:**

- [x] `datasource.md` (#7734)
- [x] `manager.md` (#7738)
- [x] `platform.md` (#7739)
- [x] `versioning.md` (#7753)

---

**`docs/usage` files:**

- [x] `automerge-configuration.md` (Skipping because I helped write this document, and it's reviewed already.)
- [x] `bazel.md` (#7754)
- [x] `config-presets.md` (#7796)
- [x] `configuration-options.md` (`#7464` is merged, I can start work on this)
- [x] `configuration-templates.md` (#7863)
- [x] `configure-renovate.md` (#7865)
- [x] `dependency-pinning.md` (#7911)
- [x] `docker.md` (#7925)
- [x] `faq.md` (#8592)
- [x] `gitlab-bot-security` (#7985)
- [x] `golang.md` (#7820)
- [x] `install-github-app.md` (#8001)
- [x] `install-gitlab-app.md`
- [x] `java.md` (#7821)
- [x] `javascript.md`
- [x] `node.md` (#7822)
- [x] `noise-reduction.md` (#7823)
- [x] `nuget.md` (#7826)
- [x] `php.md` (#7824)
- [x] `private-modules.md` (#8906)
- [x] `python.md` (#7986)
- [x] `reconfigure-renovate.md` (#8904)
- [x]  `ruby.md` (#7991)
- [x] `self-hosted-configuration.md` (#8161, #9303)
- [x] `self-hosting.md` (#8079)
- [x] `semantic-commits.md` (#8027)
- [x] `setup-azure-devops.md` (#8004)
- [x] `templates.md` (#7992)
- [x] `updating-rebasing.md` (#9021)

---

**Repository readme**

- [x] `readme.md` (#7889)

**Comment by rarkins** [comment]
These all sound great. Something else: consistent us of US vs UK english. I'm Australian so tend to write with UK spelling but I think we should have it as our policy to use US spelling where possible (e.g. Organization not Organisation, etc).

**Comment by viceice** [comment]
👍 for all those things which makes our docs better. 🙃

**Comment by HonkingGoose** [comment]
I'm finished with this! 🎉 ✨ ✨
