### ISSUE TITLE
sbt manager updating to unstable milestone releases

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#8162]
**What Renovate type, platform and version are you using?**

WhiteSource Renovate app

**Describe the bug**

Renovate updates to an unstable milestone version

**Relevant debug logs**

See https://github.com/the-benchmarker/web-frameworks/pull/3669

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [x] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

It needs to be confirmed but seems likely that we're accidentally upgrading because of the v1.0.0-M* releases: https://github.com/http4s/http4s/tags
