### ISSUE TITLE
checklist for migration from js-yaml@3 to js-yaml@4

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#8234]
## What's this?

This is a checklist for migration from `js-yaml@3` to `js-yaml@4`.
I am not going to do the migration, as I don't want to break things... 😄 

I hope this checklist is helpful for the one who is going to do the migration.
Feel free to edit my post to tick the boxes, etc (requires write level access on repo).

## Install new version of package

- [ ] Install new version of `js-yaml@4` with Yarn

## Rename old `safe*` functions:

- [ ] `safeLoad(str)` > `load(str)`
- [ ] `safeLoadAll(str)` -> `loadAll(str)`
- [ ] `yaml.safeDump(obj)` -> `yaml.dump(obj)`

So, basically remove the prefix `yaml` from the function name.

v3

```js
yaml.safeLoad(str);
yaml.safeLoadAll(str);
yaml.safeDump(obj);
```

v4

```js
yaml.load(str);
yaml.loadAll(str);
yaml.dump(obj);
```

## Old `load()`, `loadAll()`, `dump()` replaced by safe methods

- [ ] If needed: use custom extended schema to keep unsafe behavior

If we want to keep previous (unsafe) behavior, we need to use a custom extended schema:

v3

```js
yaml.load(str);
yaml.loadAll(str);
yaml.dump(obj);
```

v4

```js
let schema = yaml.DEFAULT_SCHEMA.extend(require("js-yaml-js-types").all);

yaml.load(str, { schema });
yaml.loadAll(str, { schema });
yaml.dump(obj, { schema });
```

## `Schema.create`, `DEFAULT_SAFE_SCHEMA` and `DEFAULT_FULL_SCHEMA` are removed

- [ ] `DEFAULT_SAFE_SCHEMA` -> `DEFAULT_SCHEMA`
- [ ] `DEFAULT_FULL_SCHEMA` -> `DEFAULT_SCHEMA.extend(require('js-yaml-js-types').all)`
- [ ] `Schema.create(yaml.DEFAULT_SAFE_SCHEMA, [ customTags ])` -> `DEFAULT_SCHEMA.extend([ customTags ])`

v3

```js
let schema1 = yaml.DEFAULT_SAFE_SCHEMA;
let schema2 = yaml.DEFAULT_FULL_SCHEMA;
let schema3 = yaml.Schema.create(yaml.DEFAULT_SAFE_SCHEMA, [customTags]);
```

v4

```js
let schema1 = yaml.DEFAULT_SCHEMA;
let schema2 = yaml.DEFAULT_SCHEMA.extend(require("js-yaml-js-types").all);
let schema3 = yaml.DEFAULT_SCHEMA.extend([customTags]);
```

## Check loading in v4 documents previously dumped in v3

- [ ] Read https://github.com/nodeca/js-yaml/blob/master/migrate_v3_to_v4.md#loading-in-v4-documents-previously-dumped-in-v3 for full info.
- [ ] Run `grep '\(^\|:\s\s*\)0[0-9][.0-9]*\s*$' *.yml` to check for bad pattern in our data
- [ ] If we get hits with the grep run, quote numbers with strings: `0123456789` -> `"0123456789"`

## Check module loading (reduced nesting in `lib` folder)

- [ ] Check for affected paths and fix them.

If you reference anything inside js-yaml/lib folder, i.e. `require('js-yaml/lib/XXX')`, you'll need to change paths.

v3:

```js
require("js-yaml/lib/js-yaml/common");
require("js-yaml/lib/js-yaml/type/int");
```

v4:

```js
require("js-yaml/lib/common");
require("js-yaml/lib/type/int");
```

## Check if tests need updating:

- [ ] Update tests if needed

## Reference for the checklist

https://github.com/nodeca/js-yaml/blob/master/migrate_v3_to_v4.md

**Comment by viceice** [comment]
Instead of install new versions manually we will approve the renovate major update and push required changes after renovate has opened the pr. 😉

**Comment by HonkingGoose** [comment]
> Instead of install new versions manually we will approve the renovate major update and push required changes after renovate has opened the pr. 😉

You're right, it's easier to let the bot deal with the upgrade and just push the necessary work to the bot branch.
I've updated the checklist. 😉
