### ISSUE TITLE
MultiArch Builds for RenovateBot - ARM64

### ISSUE THREAD

**Issue by dasrecht** [renovatebot/renovate#9229]
**What would you like Renovate to be able to do?**

As more and more infrastructure runs on ARM64 architecture, it would be nice to see Renovate also releasing ARM64 images.

**Did you already have any implementation ideas?**

- [x] Build all binaries (`xxx-prebuild`) repos at https://github.com/containerbase for `ARM64`
  - [ ] renovatebot/internal-tools#242
  - [x] containerbase/ruby-prebuild#7
  - [x] containerbase/python-prebuild#2
  - [x] containerbase/php-prebuild#17
  - [x] containerbase/erlang-prebuild#19
- [x] Extend docker image builder at https://github.com/containerbase/internal-tools to support building `ARM64`
  - [x] containerbase/internal-tools/issues/241
  - [x] containerbase/internal-tools#225
- [x] Build all docker image repos at https://github.com/containerbase for `ARM64` (buildpack first)
  - [x] containerbase/base#711
- [x] Build renovate docker image for `ARM64` 
  - [x] switch to use `containerbase/xxx` sidecar images
  - [x] uhop/node-re2#109
  - [x] renovatebot/docker-renovate#1207
  - [x] renovatebot/docker-renovate-full#1558

`renovatebot/xxx` sidecar images won't be ported to `ARM64` as they are already deprecated and we plan to switch to `containerbase/xxx` in near future.

**Comment by viceice** [comment]
`ls-lint` is a dev dep. I think `re2` is more an issue.

Also our full buildpack images need to be arm64 compatible first.

**Comment by viceice** [comment]
I'm the [buildpack](https://github.com/renovatebot/docker-buildpack) maintainer and not interested in ARM64, so this would need a community contribution.

**Comment by cguertin14** [comment]
+1 for this functionality. It seems like the dependency on renovate buildpack might be a problem to create multi-arch docker images, since the sha256 of the image is hardcoded in the Dockerfile here in this repo. We might need to do two separate dockerfiles, although this is not ideal.

**Comment by viceice** [comment]
You need to think about all the tools renovate uses. They all must be available for arm too. So buildpack is a big improvement for renovate tools.

Currently we are migrate the base tools to the new containerbase org. So improvements need to be done there.

**Comment by cguertin14** [comment]
@viceice ok thanks. So modifications for arm64 should be made elsewhere than https://github.com/renovatebot/docker-buildpack and https://github.com/renovatebot/docker-renovate ?

**Comment by viceice** [comment]
Yes, should be at https://github.com/containerbase

**Comment by viceice** [comment]
Also our builder needs to be able to build multi platform images

https://github.com/renovatebot/internal-tools

**Comment by rarkins** [comment]
We're shifting to github.com/containerbase for the buildpacks. For Renovate's prebuilt images to support arm64 then you'd need for each of the tools in the containerbase buildpack to support it too.

**Comment by cguertin14** [comment]
So, to resume, the following images need to me modified to support `arm64` (correct me if i'm wrong):
* https://github.com/renovatebot/internal-tools
* https://github.com/containerbase/buildpack
* https://github.com/renovatebot/docker-renovate

**Comment by JamieMagee** [comment]
That's already quite a list of things that need modified.

We'd also need a solution for CI. We use GitHub actions to run our tests, but GitHub-hosted runners only support x86.

**Comment by viceice** [comment]
@JamieMagee it's possible to build and run arm64 docker images on x86-64 docker with qemu. I already tested it, but it's very slow.

**Comment by loeffel-io** [comment]
ls-lint arm support is now in beta

**Comment by viceice** [comment]
First all `xxx-prebuild` repos at https://github.com/containerbase/ needs to publish the `arm64` binaries, i started now on https://github.com/containerbase/ruby-prebuild/pull/7 to check how it works

I started with ruby to see build time differences (arm64 emulation on amd64 docker)

**Comment by viceice** [comment]
btw: compiling ruby on github with docker qemu for arm64 is 10 times slower: ~4min => ~44min

https://github.com/containerbase/ruby-prebuild/pull/7/checks?check_run_id=3015835269

**Comment by simao-silva** [comment]
If anyone is still interest, I've managed to build for ARM64: https://github.com/simao-silva/docker-renovate

**Comment by viceice** [comment]
> If anyone is still interest, I've managed to build for ARM64: https://github.com/simao-silva/docker-renovate

Remember, that only npm is supported, as all other renovate images are not arm compatible.

**Comment by simao-silva** [comment]
> Remember, that only npm is supported, as all other renovate images are not arm compatible.

What other images are you talking about?

**Comment by viceice** [comment]
When using `binarySource=docker` renovate will start docker sidecar containers to run lockfile updates, eg `npm install`

**Comment by rarkins** [comment]
`renovate/python`, `renovate/go`, etc

**Comment by viceice** [comment]
All tools are now build / ready for `arm64` and the `containerbase/sidecar` image, which is used by renovate is multiarch (`amd64` and `arm64`) too 🎉 

The full images will be multi arch too with next renovate major

**Comment by busywhistling** [comment]
Hi, is there a beta release / branch from which we can try out (building &) running renovatebot _right now_ in arm architectures (e.g., Apple silicon)? Thanks.

**Comment by simao-silva** [comment]
@busywhistling I built a version to run on my Raspberry Pi 4: https://hub.docker.com/r/simaofsilva/renovatebot-docker-renovate/tags. However, I cannot guarantee that it will work on your environment.

**Comment by busywhistling** [comment]
Thanks @simao-silva, sadly I can't run custom images. If you could share the steps to build the image, it would be a great help though!

**Comment by viceice** [comment]
just use the official dockerfile from our docker-renovate or docker-renovate-full image and build on a arm64 docker host

**Comment by viceice** [comment]
closing, multiarch images should be available soon
